server:
  port: 8090
  
spring:  application:    name: notification
  datasource:
        username: amigoscode
        url: jdbc:postgresql://localhost:5432/NotificationDb
        password: password
  jpa:
      hibernate:
          ddl-auto: create-drop
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
              format_sql: true
      show-sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka